"""updating compartment table

Revision ID: 21b969ab8ec9
Revises: e22ab07d073b
Create Date: 2018-12-06 14:27:15.260023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b969ab8ec9'
down_revision = 'e22ab07d073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compartment', sa.Column('bigg_acronym', sa.String(), nullable=True))
    op.add_column('compartment', sa.Column('metanetx_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_compartment_id'), 'compartment', ['id'], unique=True)
    op.drop_constraint('compartment_acronym_key', 'compartment', type_='unique')
    op.create_unique_constraint(None, 'compartment', ['metanetx_id'])
    op.create_unique_constraint(None, 'compartment', ['bigg_acronym'])
    op.drop_column('compartment', 'acronym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compartment', sa.Column('acronym', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'compartment', type_='unique')
    op.drop_constraint(None, 'compartment', type_='unique')
    op.create_unique_constraint('compartment_acronym_key', 'compartment', ['acronym'])
    op.drop_index(op.f('ix_compartment_id'), table_name='compartment')
    op.drop_column('compartment', 'metanetx_id')
    op.drop_column('compartment', 'bigg_acronym')
    # ### end Alembic commands ###
