"""poplaying with enzyme 2

Revision ID: 4eb9daf93d03
Revises: 6952538c0e96
Create Date: 2018-11-13 17:35:24.168498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb9daf93d03'
down_revision = '6952538c0e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enzyme_gene')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enzyme_gene',
    sa.Column('enzyme_id', sa.INTEGER(), nullable=True),
    sa.Column('gene_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['enzyme_id'], ['enzyme.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], )
    )
    # ### end Alembic commands ###
