"""added timestamp to gene and enzyme

Revision ID: 534ed10b239f
Revises: ef3e1faa8c90
Create Date: 2018-11-15 13:38:44.118671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534ed10b239f'
down_revision = 'ef3e1faa8c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enzyme', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_enzyme_timestamp'), 'enzyme', ['timestamp'], unique=False)
    op.add_column('gene', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_gene_timestamp'), 'gene', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_timestamp'), table_name='gene')
    op.drop_column('gene', 'timestamp')
    op.drop_index(op.f('ix_enzyme_timestamp'), table_name='enzyme')
    op.drop_column('enzyme', 'timestamp')
    # ### end Alembic commands ###
