"""poenzyme and gene tables

Revision ID: 6952538c0e96
Revises: faf4debf43a3
Create Date: 2018-11-13 17:25:46.363412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6952538c0e96'
down_revision = 'faf4debf43a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enzyme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('isoenzyme', sa.String(), nullable=True),
    sa.Column('ec_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bigg_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enzyme_gene',
    sa.Column('enzyme_id', sa.Integer(), nullable=True),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enzyme_id'], ['enzyme.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enzyme_gene')
    op.drop_table('gene')
    op.drop_table('enzyme')
    # ### end Alembic commands ###
