"""updating ids for metabolites and reactions

Revision ID: ddfdc6cdce05
Revises: 21b969ab8ec9
Create Date: 2018-12-11 14:12:00.621435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfdc6cdce05'
down_revision = '21b969ab8ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metabolite', 'kegg_id')
    op.drop_column('reaction', 'reactome_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('reactome_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metabolite', sa.Column('kegg_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
