"""added connection between enzyme and gene

Revision ID: ef3e1faa8c90
Revises: 4eb9daf93d03
Create Date: 2018-11-15 13:14:45.274860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3e1faa8c90'
down_revision = '4eb9daf93d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enzyme_gene',
    sa.Column('enzyme_id', sa.Integer(), nullable=True),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enzyme_id'], ['enzyme.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enzyme_gene')
    # ### end Alembic commands ###
